/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Exercise {
    icon: string;
    name: string;
    reps: bigint;
    sets: bigint;
    description: string;
    exerciseType: ExerciseType;
    videoUrl?: string;
}
export interface CoolDownActivity {
    name: string;
    completed: boolean;
    durationMinutes: number;
}
export interface SetSpecificWeight {
    weight: number;
    exerciseName: string;
    setIndex: bigint;
}
export type Time = bigint;
export interface WarmUpActivity {
    name: string;
    completed: boolean;
    durationMinutes: number;
}
export interface WorkoutSession {
    sessionType: string;
    date: Time;
    exercises: Array<ExerciseLog>;
    coolDownActivities: Array<CoolDownActivity>;
    warmUpActivities: Array<WarmUpActivity>;
}
export interface SetLog {
    weight: number;
    reps: bigint;
}
export interface ExerciseLog {
    name: string;
    sets: Array<SetLog>;
}
export interface UserProfile {
    experienceLevel: ExperienceLevel;
    unlockedSessions: Array<string>;
    startDate: Time;
}
export enum ExerciseType {
    bodyweight = "bodyweight",
    barbell = "barbell",
    dumbbell = "dumbbell"
}
export enum ExperienceLevel {
    intermediate = "intermediate",
    beginner = "beginner"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteWorkoutSession(date: Time, sessionType: string): Promise<void>;
    getAvailableSessions(): Promise<Array<string>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCoolDownActivities(): Promise<Array<CoolDownActivity>>;
    getCurrentExperienceLevel(): Promise<ExperienceLevel>;
    getDefaultSetStructure(): Promise<{
        mainLifts: Array<SetLog>;
        supplementalLifts: Array<SetLog>;
    }>;
    getLastUsedWeightForSet(exerciseName: string, setIndex: bigint): Promise<number | null>;
    getLastUsedWeightsForExercise(exerciseName: string): Promise<Array<number>>;
    getSessionAExercises(): Promise<Array<Exercise>>;
    getSessionBExercises(): Promise<Array<Exercise>>;
    getSetSpecificWeights(): Promise<Array<SetSpecificWeight>>;
    getTechniqueCues(): Promise<Array<string>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWarmUpActivities(): Promise<Array<WarmUpActivity>>;
    getWorkoutHistory(): Promise<Array<WorkoutSession>>;
    getWorkoutProgress(): Promise<bigint>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveWorkoutSession(session: WorkoutSession): Promise<void>;
    /**
     * / Update or add an entire workout session for the current caller.
     */
    upsertWorkoutSession(session: WorkoutSession): Promise<void>;
}
import type { Exercise as _Exercise, ExerciseType as _ExerciseType, ExperienceLevel as _ExperienceLevel, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async deleteWorkoutSession(arg0: Time, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteWorkoutSession(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteWorkoutSession(arg0, arg1);
            return result;
        }
    }
    async getAvailableSessions(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableSessions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableSessions();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n8(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n8(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCoolDownActivities(): Promise<Array<CoolDownActivity>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoolDownActivities();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoolDownActivities();
            return result;
        }
    }
    async getCurrentExperienceLevel(): Promise<ExperienceLevel> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentExperienceLevel();
                return from_candid_ExperienceLevel_n6(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentExperienceLevel();
            return from_candid_ExperienceLevel_n6(this.uploadFile, this.downloadFile, result);
        }
    }
    async getDefaultSetStructure(): Promise<{
        mainLifts: Array<SetLog>;
        supplementalLifts: Array<SetLog>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getDefaultSetStructure();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDefaultSetStructure();
            return result;
        }
    }
    async getLastUsedWeightForSet(arg0: string, arg1: bigint): Promise<number | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLastUsedWeightForSet(arg0, arg1);
                return from_candid_opt_n10(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLastUsedWeightForSet(arg0, arg1);
            return from_candid_opt_n10(this.uploadFile, this.downloadFile, result);
        }
    }
    async getLastUsedWeightsForExercise(arg0: string): Promise<Array<number>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLastUsedWeightsForExercise(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLastUsedWeightsForExercise(arg0);
            return result;
        }
    }
    async getSessionAExercises(): Promise<Array<Exercise>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSessionAExercises();
                return from_candid_vec_n11(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSessionAExercises();
            return from_candid_vec_n11(this.uploadFile, this.downloadFile, result);
        }
    }
    async getSessionBExercises(): Promise<Array<Exercise>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSessionBExercises();
                return from_candid_vec_n11(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSessionBExercises();
            return from_candid_vec_n11(this.uploadFile, this.downloadFile, result);
        }
    }
    async getSetSpecificWeights(): Promise<Array<SetSpecificWeight>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSetSpecificWeights();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSetSpecificWeights();
            return result;
        }
    }
    async getTechniqueCues(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTechniqueCues();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTechniqueCues();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this.uploadFile, this.downloadFile, result);
        }
    }
    async getWarmUpActivities(): Promise<Array<WarmUpActivity>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWarmUpActivities();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWarmUpActivities();
            return result;
        }
    }
    async getWorkoutHistory(): Promise<Array<WorkoutSession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkoutHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkoutHistory();
            return result;
        }
    }
    async getWorkoutProgress(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkoutProgress();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkoutProgress();
            return result;
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n17(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n17(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async saveWorkoutSession(arg0: WorkoutSession): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveWorkoutSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveWorkoutSession(arg0);
            return result;
        }
    }
    async upsertWorkoutSession(arg0: WorkoutSession): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.upsertWorkoutSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upsertWorkoutSession(arg0);
            return result;
        }
    }
}
function from_candid_ExerciseType_n14(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExerciseType): ExerciseType {
    return from_candid_variant_n15(uploadFile, downloadFile, value);
}
function from_candid_Exercise_n12(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Exercise): Exercise {
    return from_candid_record_n13(uploadFile, downloadFile, value);
}
function from_candid_ExperienceLevel_n6(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExperienceLevel): ExperienceLevel {
    return from_candid_variant_n7(uploadFile, downloadFile, value);
}
function from_candid_UserProfile_n4(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n5(uploadFile, downloadFile, value);
}
function from_candid_UserRole_n8(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n9(uploadFile, downloadFile, value);
}
function from_candid_opt_n10(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n4(uploadFile, downloadFile, value[0]);
}
function from_candid_record_n13(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    icon: string;
    name: string;
    reps: bigint;
    sets: bigint;
    description: string;
    exerciseType: _ExerciseType;
    videoUrl: [] | [string];
}): {
    icon: string;
    name: string;
    reps: bigint;
    sets: bigint;
    description: string;
    exerciseType: ExerciseType;
    videoUrl?: string;
} {
    return {
        icon: value.icon,
        name: value.name,
        reps: value.reps,
        sets: value.sets,
        description: value.description,
        exerciseType: from_candid_ExerciseType_n14(uploadFile, downloadFile, value.exerciseType),
        videoUrl: record_opt_to_undefined(from_candid_opt_n16(uploadFile, downloadFile, value.videoUrl))
    };
}
function from_candid_record_n5(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    experienceLevel: _ExperienceLevel;
    unlockedSessions: Array<string>;
    startDate: _Time;
}): {
    experienceLevel: ExperienceLevel;
    unlockedSessions: Array<string>;
    startDate: Time;
} {
    return {
        experienceLevel: from_candid_ExperienceLevel_n6(uploadFile, downloadFile, value.experienceLevel),
        unlockedSessions: value.unlockedSessions,
        startDate: value.startDate
    };
}
function from_candid_variant_n15(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bodyweight: null;
} | {
    barbell: null;
} | {
    dumbbell: null;
}): ExerciseType {
    return "bodyweight" in value ? ExerciseType.bodyweight : "barbell" in value ? ExerciseType.barbell : "dumbbell" in value ? ExerciseType.dumbbell : value;
}
function from_candid_variant_n7(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    intermediate: null;
} | {
    beginner: null;
}): ExperienceLevel {
    return "intermediate" in value ? ExperienceLevel.intermediate : "beginner" in value ? ExperienceLevel.beginner : value;
}
function from_candid_variant_n9(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n11(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Exercise>): Array<Exercise> {
    return value.map((x)=>from_candid_Exercise_n12(uploadFile, downloadFile, x));
}
function to_candid_ExperienceLevel_n19(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExperienceLevel): _ExperienceLevel {
    return to_candid_variant_n20(uploadFile, downloadFile, value);
}
function to_candid_UserProfile_n17(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n18(uploadFile, downloadFile, value);
}
function to_candid_UserRole_n1(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(uploadFile, downloadFile, value);
}
function to_candid_record_n18(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    experienceLevel: ExperienceLevel;
    unlockedSessions: Array<string>;
    startDate: Time;
}): {
    experienceLevel: _ExperienceLevel;
    unlockedSessions: Array<string>;
    startDate: _Time;
} {
    return {
        experienceLevel: to_candid_ExperienceLevel_n19(uploadFile, downloadFile, value.experienceLevel),
        unlockedSessions: value.unlockedSessions,
        startDate: value.startDate
    };
}
function to_candid_variant_n2(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n20(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExperienceLevel): {
    intermediate: null;
} | {
    beginner: null;
} {
    return value == ExperienceLevel.intermediate ? {
        intermediate: null
    } : value == ExperienceLevel.beginner ? {
        beginner: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, uploadFile, downloadFile, options.processError);
}
