/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const ExperienceLevel = IDL.Variant({
  'intermediate' : IDL.Null,
  'beginner' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'experienceLevel' : ExperienceLevel,
  'unlockedSessions' : IDL.Vec(IDL.Text),
  'startDate' : Time,
});
export const CoolDownActivity = IDL.Record({
  'name' : IDL.Text,
  'completed' : IDL.Bool,
  'durationMinutes' : IDL.Float64,
});
export const SetLog = IDL.Record({ 'weight' : IDL.Float64, 'reps' : IDL.Nat });
export const ExerciseType = IDL.Variant({
  'bodyweight' : IDL.Null,
  'barbell' : IDL.Null,
  'dumbbell' : IDL.Null,
});
export const Exercise = IDL.Record({
  'icon' : IDL.Text,
  'name' : IDL.Text,
  'reps' : IDL.Nat,
  'sets' : IDL.Nat,
  'description' : IDL.Text,
  'exerciseType' : ExerciseType,
  'videoUrl' : IDL.Opt(IDL.Text),
});
export const SetSpecificWeight = IDL.Record({
  'weight' : IDL.Float64,
  'exerciseName' : IDL.Text,
  'setIndex' : IDL.Nat,
});
export const WarmUpActivity = IDL.Record({
  'name' : IDL.Text,
  'completed' : IDL.Bool,
  'durationMinutes' : IDL.Float64,
});
export const ExerciseLog = IDL.Record({
  'name' : IDL.Text,
  'sets' : IDL.Vec(SetLog),
});
export const WorkoutSession = IDL.Record({
  'sessionType' : IDL.Text,
  'date' : Time,
  'exercises' : IDL.Vec(ExerciseLog),
  'coolDownActivities' : IDL.Vec(CoolDownActivity),
  'warmUpActivities' : IDL.Vec(WarmUpActivity),
});

export const idlService = IDL.Service({
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteWorkoutSession' : IDL.Func([Time, IDL.Text], [], []),
  'getAvailableSessions' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCoolDownActivities' : IDL.Func(
      [],
      [IDL.Vec(CoolDownActivity)],
      ['query'],
    ),
  'getCurrentExperienceLevel' : IDL.Func([], [ExperienceLevel], ['query']),
  'getDefaultSetStructure' : IDL.Func(
      [],
      [
        IDL.Record({
          'mainLifts' : IDL.Vec(SetLog),
          'supplementalLifts' : IDL.Vec(SetLog),
        }),
      ],
      ['query'],
    ),
  'getLastUsedWeightForSet' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Opt(IDL.Float64)],
      ['query'],
    ),
  'getLastUsedWeightsForExercise' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Float64)],
      ['query'],
    ),
  'getSessionAExercises' : IDL.Func([], [IDL.Vec(Exercise)], ['query']),
  'getSessionBExercises' : IDL.Func([], [IDL.Vec(Exercise)], ['query']),
  'getSetSpecificWeights' : IDL.Func(
      [],
      [IDL.Vec(SetSpecificWeight)],
      ['query'],
    ),
  'getTechniqueCues' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWarmUpActivities' : IDL.Func([], [IDL.Vec(WarmUpActivity)], ['query']),
  'getWorkoutHistory' : IDL.Func([], [IDL.Vec(WorkoutSession)], ['query']),
  'getWorkoutProgress' : IDL.Func([], [IDL.Nat], ['query']),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveWorkoutSession' : IDL.Func([WorkoutSession], [], []),
  'upsertWorkoutSession' : IDL.Func([WorkoutSession], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const ExperienceLevel = IDL.Variant({
    'intermediate' : IDL.Null,
    'beginner' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'experienceLevel' : ExperienceLevel,
    'unlockedSessions' : IDL.Vec(IDL.Text),
    'startDate' : Time,
  });
  const CoolDownActivity = IDL.Record({
    'name' : IDL.Text,
    'completed' : IDL.Bool,
    'durationMinutes' : IDL.Float64,
  });
  const SetLog = IDL.Record({ 'weight' : IDL.Float64, 'reps' : IDL.Nat });
  const ExerciseType = IDL.Variant({
    'bodyweight' : IDL.Null,
    'barbell' : IDL.Null,
    'dumbbell' : IDL.Null,
  });
  const Exercise = IDL.Record({
    'icon' : IDL.Text,
    'name' : IDL.Text,
    'reps' : IDL.Nat,
    'sets' : IDL.Nat,
    'description' : IDL.Text,
    'exerciseType' : ExerciseType,
    'videoUrl' : IDL.Opt(IDL.Text),
  });
  const SetSpecificWeight = IDL.Record({
    'weight' : IDL.Float64,
    'exerciseName' : IDL.Text,
    'setIndex' : IDL.Nat,
  });
  const WarmUpActivity = IDL.Record({
    'name' : IDL.Text,
    'completed' : IDL.Bool,
    'durationMinutes' : IDL.Float64,
  });
  const ExerciseLog = IDL.Record({
    'name' : IDL.Text,
    'sets' : IDL.Vec(SetLog),
  });
  const WorkoutSession = IDL.Record({
    'sessionType' : IDL.Text,
    'date' : Time,
    'exercises' : IDL.Vec(ExerciseLog),
    'coolDownActivities' : IDL.Vec(CoolDownActivity),
    'warmUpActivities' : IDL.Vec(WarmUpActivity),
  });
  
  return IDL.Service({
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteWorkoutSession' : IDL.Func([Time, IDL.Text], [], []),
    'getAvailableSessions' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCoolDownActivities' : IDL.Func(
        [],
        [IDL.Vec(CoolDownActivity)],
        ['query'],
      ),
    'getCurrentExperienceLevel' : IDL.Func([], [ExperienceLevel], ['query']),
    'getDefaultSetStructure' : IDL.Func(
        [],
        [
          IDL.Record({
            'mainLifts' : IDL.Vec(SetLog),
            'supplementalLifts' : IDL.Vec(SetLog),
          }),
        ],
        ['query'],
      ),
    'getLastUsedWeightForSet' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Opt(IDL.Float64)],
        ['query'],
      ),
    'getLastUsedWeightsForExercise' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Float64)],
        ['query'],
      ),
    'getSessionAExercises' : IDL.Func([], [IDL.Vec(Exercise)], ['query']),
    'getSessionBExercises' : IDL.Func([], [IDL.Vec(Exercise)], ['query']),
    'getSetSpecificWeights' : IDL.Func(
        [],
        [IDL.Vec(SetSpecificWeight)],
        ['query'],
      ),
    'getTechniqueCues' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWarmUpActivities' : IDL.Func([], [IDL.Vec(WarmUpActivity)], ['query']),
    'getWorkoutHistory' : IDL.Func([], [IDL.Vec(WorkoutSession)], ['query']),
    'getWorkoutProgress' : IDL.Func([], [IDL.Nat], ['query']),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveWorkoutSession' : IDL.Func([WorkoutSession], [], []),
    'upsertWorkoutSession' : IDL.Func([WorkoutSession], [], []),
  });
};

export const init = ({ IDL }) => { return []; };