/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CoolDownActivity {
  'name' : string,
  'completed' : boolean,
  'durationMinutes' : number,
}
export interface Exercise {
  'icon' : string,
  'name' : string,
  'reps' : bigint,
  'sets' : bigint,
  'description' : string,
  'exerciseType' : ExerciseType,
  'videoUrl' : [] | [string],
}
export interface ExerciseLog { 'name' : string, 'sets' : Array<SetLog> }
export type ExerciseType = { 'bodyweight' : null } |
  { 'barbell' : null } |
  { 'dumbbell' : null };
export type ExperienceLevel = { 'intermediate' : null } |
  { 'beginner' : null };
export interface SetLog { 'weight' : number, 'reps' : bigint }
export interface SetSpecificWeight {
  'weight' : number,
  'exerciseName' : string,
  'setIndex' : bigint,
}
export type Time = bigint;
export interface UserProfile {
  'experienceLevel' : ExperienceLevel,
  'unlockedSessions' : Array<string>,
  'startDate' : Time,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WarmUpActivity {
  'name' : string,
  'completed' : boolean,
  'durationMinutes' : number,
}
export interface WorkoutSession {
  'sessionType' : string,
  'date' : Time,
  'exercises' : Array<ExerciseLog>,
  'coolDownActivities' : Array<CoolDownActivity>,
  'warmUpActivities' : Array<WarmUpActivity>,
}
export interface _SERVICE {
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteWorkoutSession' : ActorMethod<[Time, string], undefined>,
  'getAvailableSessions' : ActorMethod<[], Array<string>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCoolDownActivities' : ActorMethod<[], Array<CoolDownActivity>>,
  'getCurrentExperienceLevel' : ActorMethod<[], ExperienceLevel>,
  'getDefaultSetStructure' : ActorMethod<
    [],
    { 'mainLifts' : Array<SetLog>, 'supplementalLifts' : Array<SetLog> }
  >,
  'getLastUsedWeightForSet' : ActorMethod<[string, bigint], [] | [number]>,
  'getLastUsedWeightsForExercise' : ActorMethod<[string], Array<number>>,
  'getSessionAExercises' : ActorMethod<[], Array<Exercise>>,
  'getSessionBExercises' : ActorMethod<[], Array<Exercise>>,
  'getSetSpecificWeights' : ActorMethod<[], Array<SetSpecificWeight>>,
  'getTechniqueCues' : ActorMethod<[], Array<string>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWarmUpActivities' : ActorMethod<[], Array<WarmUpActivity>>,
  'getWorkoutHistory' : ActorMethod<[], Array<WorkoutSession>>,
  'getWorkoutProgress' : ActorMethod<[], bigint>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveWorkoutSession' : ActorMethod<[WorkoutSession], undefined>,
  /**
   * / Update or add an entire workout session for the current caller.
   */
  'upsertWorkoutSession' : ActorMethod<[WorkoutSession], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];